# Plugin by https://fazziclay.ru/
# Use https://minecraftjson.com to generate Minecraft JSONComponent.

unregisterCommands:
  - seed
  - pl
  - plugins
  - version
  - ver

message:
  enable: true
  joinPlayer: '{"translate":"multiplayer.player.joined", ,"color":"yellow", "with":[{"text":"%player_nickname%","clickEvent":{"action":"suggest_command","value":"/tell %player_nickname% "},"hoverEvent":{"action":"show_text","contents":["Click to send a private message!"]}}]}'
  leavePlayer: '{"translate":"multiplayer.player.left", "color":"yellow", "with": ["%player_nickname%"]}'

directMessage:
  enable: true
  commands:
    - tell
    - msg
    - w

  senderPattern: '{"text":"Message sent!","color":"dark_green","clickEvent":{"action":"suggest_command","value":"/tell %recipient_nickname% "},"hoverEvent":{"action":"show_text","contents":[{"text":"---- Private Message ----","color":"dark_green"},"\n","%sender_nickname% -> %recipient_nickname%","\n","\n","%message_content%"]}}'
  recipientPattern: '{"text":"%sender_nickname% -> %recipient_nickname%: %message_content%","color":"gray","clickEvent":{"action":"suggest_command","value":"/tell %recipient_nickname% "},"hoverEvent":{"action":"show_text","contents":[{"text":"---- Private Message ----","color":"dark_green"},"\n","%sender_nickname% -> %recipient_nickname%","\n","\n","%message_content%"]}}'
  playerNotFound: '{"translate":"argument.entity.notfound.player","color":"red"}'

  argumentsName: ["recipient", "message"]

chat:
  list: [example]
  default: example

  example:
    range: 50
    prefix: none
    messageType: chat
    pattern: '[{"translate":"chat.type.text","with":[{"text":"%sender_name%","clickEvent":{"action":"suggest_command","value":"/tell %sender_name% "},"hoverEvent":{"action":"show_text","contents":["Click to send a private message!"]}},"%message_content%"]}]'

version: 0