messages:
  joinPlayer: '["",{"text":"%player_nickname%","color":"yellow","clickEvent":{"action":"suggest_command","value":"tell %player_nickname%"},"hoverEvent":{"action":"show_text","contents":"Click to send DM"}},{"text":" join to server!","color":"yellow"}]'
  leavePlayer: '{"text":"%player_nickname% leave from server!","color":"yellow"}'
  kickPlayer: '%player_nickname% Kicked from this server!'

chat:
  list: [local, global, roleplay, anynamechatname]
  default: local

  local:
    range: 50
    prefix: none
    messageType: chat
    pattern: '[{"translate":"chat.type.text","with":[{"text":"%player_nickname%","clickEvent":{"action":"suggest_command","value":"/tell %player_nickname% "},"hoverEvent":{"action":"show_text","contents":["Click to send a private message"]}},"%message_content%"]}]'

  global:
    range: -1
    prefix: "!"
    messageType: chat
    pattern: '[{"text": "[G]", "color": "gray"}, {"text": " "}, {"translate":"chat.type.text","with":[{"text":"%player_nickname%","clickEvent":{"action":"suggest_command","value":"/tell %player_nickname% "},"hoverEvent":{"action":"show_text","contents":["Click to send a private message"]}},"%message_content%"]}]'

  roleplay:
    range: 50
    prefix: "*"
    messageType: chat
    pattern: '[{"text": "*%player_nickname% %message_content%*"}]'

  anynamechatname:
    range: 10
    messageType: system
    prefix: "-"
    pattern: '[{"text": "[Example] %player_nickname%: %message_content%", "color": "red", "italic": true}]'


version: 0