name: "OpenSpigotChat"
description: "Super Spigot Chat Plugin"
author: "https://fazziclay.ru/"
website: "https://github.com/fazziclay/OpenSpigotChat/"
main: "ru.fazziclay.openspigotchat.OpenSpigotChat"
api-version: 1.13
load: STARTUP
version: "0.1"
